/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectNameRouteImport } from './routes/project/$name'
import { Route as ProjectNameIndexRouteImport } from './routes/project/$name/index'
import { Route as ProjectNameEditorRouteImport } from './routes/project/$name/editor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectNameRoute = ProjectNameRouteImport.update({
  id: '/project/$name',
  path: '/project/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectNameIndexRoute = ProjectNameIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectNameRoute,
} as any)
const ProjectNameEditorRoute = ProjectNameEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => ProjectNameRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/project/$name': typeof ProjectNameRouteWithChildren
  '/project/$name/editor': typeof ProjectNameEditorRoute
  '/project/$name/': typeof ProjectNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/project/$name/editor': typeof ProjectNameEditorRoute
  '/project/$name': typeof ProjectNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/project/$name': typeof ProjectNameRouteWithChildren
  '/project/$name/editor': typeof ProjectNameEditorRoute
  '/project/$name/': typeof ProjectNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/project/$name'
    | '/project/$name/editor'
    | '/project/$name/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/project/$name/editor' | '/project/$name'
  id:
    | '__root__'
    | '/'
    | '/project/$name'
    | '/project/$name/editor'
    | '/project/$name/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectNameRoute: typeof ProjectNameRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$name': {
      id: '/project/$name'
      path: '/project/$name'
      fullPath: '/project/$name'
      preLoaderRoute: typeof ProjectNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$name/': {
      id: '/project/$name/'
      path: '/'
      fullPath: '/project/$name/'
      preLoaderRoute: typeof ProjectNameIndexRouteImport
      parentRoute: typeof ProjectNameRoute
    }
    '/project/$name/editor': {
      id: '/project/$name/editor'
      path: '/editor'
      fullPath: '/project/$name/editor'
      preLoaderRoute: typeof ProjectNameEditorRouteImport
      parentRoute: typeof ProjectNameRoute
    }
  }
}

interface ProjectNameRouteChildren {
  ProjectNameEditorRoute: typeof ProjectNameEditorRoute
  ProjectNameIndexRoute: typeof ProjectNameIndexRoute
}

const ProjectNameRouteChildren: ProjectNameRouteChildren = {
  ProjectNameEditorRoute: ProjectNameEditorRoute,
  ProjectNameIndexRoute: ProjectNameIndexRoute,
}

const ProjectNameRouteWithChildren = ProjectNameRoute._addFileChildren(
  ProjectNameRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectNameRoute: ProjectNameRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
